import os

configfile: "config.yaml"


INPUT_DIR = config["directories"]["inputs"]
TRIM_DIR = config["directories"]["trim_fastq"]
TRIM_REPORT_DIR = config["directories"]["trim_reports"]
SUMMARY_DIR = config["directories"]["summary"]

TRIM_CUTOFF = config["parameters"]["trim_cutoff"]

files = glob_wildcards(os.path.join(INPUT_DIR, "{sample}_{primer}.ab1"))
samples, primers = files.sample, files.primer


rule all:
    input:
        expand(os.path.join(TRIM_DIR, "{sample}_{primer}_trimmed.fastq"), zip, sample=samples, primer=primers),
        os.path.join(SUMMARY_DIR, "trim_metrics.tsv")


rule trim:
    input:
        os.path.join(INPUT_DIR, "{sample}_{primer}.ab1")
    output:
        fastq = os.path.join(TRIM_DIR, "{sample}_{primer}_trimmed.fastq"),
        report = os.path.join(TRIM_REPORT_DIR, "{sample}_{primer}_trim_report.tsv")
    params:
        cutoff = TRIM_CUTOFF
    shell:
        "python3 scripts/trim.py -i {input} -o {output.fastq} --output_report {output.report} --trim_cutoff {params.cutoff}"


rule trim_aggregate:
    input:
        reports = expand(os.path.join(TRIM_REPORT_DIR, "1_trim", "{sample}_{primer}_trim_report.tsv"), 
               zip, sample=samples, primer=primers)
    output:
        summary = os.path.join(SUMMARY_DIR, "trim_metrics.tsv")
    run:
        import pandas as pd
        dfs = [pd.read_csv(f, sep='\t') for f in input.reports]
        final_df = pd.concat(dfs, ignore_index=True)
        final_df.to_csv(output.summary, sep='\t', index=False)

